### ISSUE TITLE
Breeding GUI Assumes Box Count of 30

### ISSUE THREAD

**Issue by soupbag** [ThomasQTruong/VeryScuffedCobblemonBreeding#1]
Hi there,

The /pokebreed GUI seems to assume the defaultBoxCount is 30, even when it's configured to be higher. Clicking previous box from the start leads to box 30, while pressing next box forward eventually runs up to 30 and back to 1

Thanks for all that you do!

**Comment by ThomasQTruong** [comment]
Hello! I was not aware of that initially, thank you for letting me know! The new update now support more boxes than default.
