### ISSUE TITLE
Confused about how hidden abilities work.

### ISSUE THREAD

**Issue by RulOfficial** [ThomasQTruong/VeryScuffedCobblemonBreeding#11]
Hidden abilities are not supported on the cobblemon mod, so I decided to use your mod and hope that by breeding pokemons I would get one with a hidden ability, I have read in the mod description that abilities are randomized while breeding, does that mean that I could get a hidden ability from breeding two pokemon with non-hidden abilities ? 

If the answer is "Yes," is there any config to change the chance of hidden abilities to pop-up in each breeding process?

**Comment by ThomasQTruong** [comment]
Hello, breeding two non-hidden ability pokemons will not yield a hidden ability child. That feature is mainly for servers that have a system in obtaining HAs already (i.e. tournaments).
