### ISSUE TITLE
Can't breed perfect IV cobblemon - stats seem to drop to 0 when it should have worked.

### ISSUE THREAD

**Issue by KangaliaV** [ThomasQTruong/VeryScuffedCobblemonBreeding#5]
Problem: Can't seem to breed perfect IV cobblemon. Whenever a cobblemon seems it should have perfect stats, one of it's stats randomly drops to 0. 
![image](https://user-images.githubusercontent.com/50462107/235377481-6ea0af32-2b40-43e0-8d28-fb6193742685.png)

**Comment by ThomasQTruong** [comment]
sorry, i did not see this, but it happens if the mod cannot pull the proper stat from the cobblemon due to a bug or something going on with the cobblemon.
