### ISSUE TITLE
Cobblemon breeding items do not work

### ISSUE THREAD

**Issue by Astral1470** [ThomasQTruong/VeryScuffedCobblemonBreeding#9]
Cobblemon v1.4.0 added Power items and the Destiny Knot. It has had the Everstone for several versions. These lack the nbt tags needed for this mod to consider them as breeding items.

It wouldn't make sense for Cobblemon to add random nbt data to these held items in its crafting recipe, so this mod should probably look at the name or item id instead of nbt data.

**Comment by ThomasQTruong** [comment]
Added support for v1.4.0's breeding items! :)
